/**
 * generated by Xtext 2.13.0
 */
package nii.bigclout.ecaadapter.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mapping Pair</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nii.bigclout.ecaadapter.dsl.MappingPair#getResource <em>Resource</em>}</li>
 *   <li>{@link nii.bigclout.ecaadapter.dsl.MappingPair#getState <em>State</em>}</li>
 *   <li>{@link nii.bigclout.ecaadapter.dsl.MappingPair#getActionCode <em>Action Code</em>}</li>
 * </ul>
 *
 * @see nii.bigclout.ecaadapter.dsl.DslPackage#getMappingPair()
 * @model
 * @generated
 */
public interface MappingPair extends EObject
{
  /**
   * Returns the value of the '<em><b>Resource</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Resource</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resource</em>' reference.
   * @see #setResource(Resource)
   * @see nii.bigclout.ecaadapter.dsl.DslPackage#getMappingPair_Resource()
   * @model
   * @generated
   */
  Resource getResource();

  /**
   * Sets the value of the '{@link nii.bigclout.ecaadapter.dsl.MappingPair#getResource <em>Resource</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resource</em>' reference.
   * @see #getResource()
   * @generated
   */
  void setResource(Resource value);

  /**
   * Returns the value of the '<em><b>State</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>State</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>State</em>' containment reference.
   * @see #setState(Element)
   * @see nii.bigclout.ecaadapter.dsl.DslPackage#getMappingPair_State()
   * @model containment="true"
   * @generated
   */
  Element getState();

  /**
   * Sets the value of the '{@link nii.bigclout.ecaadapter.dsl.MappingPair#getState <em>State</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State</em>' containment reference.
   * @see #getState()
   * @generated
   */
  void setState(Element value);

  /**
   * Returns the value of the '<em><b>Action Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Action Code</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action Code</em>' attribute.
   * @see #setActionCode(String)
   * @see nii.bigclout.ecaadapter.dsl.DslPackage#getMappingPair_ActionCode()
   * @model
   * @generated
   */
  String getActionCode();

  /**
   * Sets the value of the '{@link nii.bigclout.ecaadapter.dsl.MappingPair#getActionCode <em>Action Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action Code</em>' attribute.
   * @see #getActionCode()
   * @generated
   */
  void setActionCode(String value);

} // MappingPair
