/**
 * generated by Xtext 2.13.0
 */
package nii.bigclout.ecaadapter.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Metadata</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see nii.bigclout.ecaadapter.dsl.DslPackage#getMetadata()
 * @model
 * @generated
 */
public interface Metadata extends EObject
{
} // Metadata
