/**
 * generated by Xtext 2.13.0
 */
package nii.bigclout.ecaadapter.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nii.bigclout.ecaadapter.dsl.String_Object#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see nii.bigclout.ecaadapter.dsl.DslPackage#getString_Object()
 * @model
 * @generated
 */
public interface String_Object extends Element
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see nii.bigclout.ecaadapter.dsl.DslPackage#getString_Object_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link nii.bigclout.ecaadapter.dsl.String_Object#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // String_Object
