/*
 * generated by Xtext 2.13.0
 */
package nii.bigclout.ecaadapter.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslScopeProvider extends DelegatingScopeProvider {
}
