/*
 * generated by Xtext 2.13.0
 */
package nii.bigclout.ecaadapter.validation

import nii.bigclout.ecaadapter.dsl.RunTimeModel
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class DslValidator extends AbstractDslValidator {
	
	public static val DUPLICATE_NAME = 'duplicateName'
/*
	@Check
	def checkGreetingStartsWithCapital(RunTimeModel model) {
		if (!Character.isUpperCase(greeting.name.charAt(0))) {
			warning('Name should start with a capital', 
					DslPackage.Literals.GREETING__NAME,
					INVALID_NAME)
		}
	}
*/
	
}
