/**
 * generated by Xtext 2.13.0
 */
package nii.bigclout.ecaadapter.ide;

import com.google.inject.Injector;
import nii.bigclout.ecaadapter.DslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DslIdeSetup extends DslStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from DslRuntimeModule to Module"
      + "\nType mismatch: cannot convert from DslIdeModule to Module");
  }
}
