/**
 * generated by Xtext 2.13.0
 */
package nii.bigclout.ecaadapter;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DslStandaloneSetup /* implements DslStandaloneSetupGenerated  */{
  public static void doSetup() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type DslStandaloneSetup");
  }
}
