/*
 * generated by Xtext 2.13.0
 */
package nii.bigclout.ecaadapter.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class RunTimeModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.RunTimeModel");
		private final Assignment cAppDataAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cAppDataAppMetaDataParserRuleCall_0 = (RuleCall)cAppDataAssignment.eContents().get(0);
		
		//RunTimeModel:
		//	appData+=AppMetaData*
		//	//envData += EnvironmentMetaData*	
		//;
		@Override public ParserRule getRule() { return rule; }
		
		////servicesData += ServiceMetaData*  
		//appData+=AppMetaData*
		public Assignment getAppDataAssignment() { return cAppDataAssignment; }
		
		//AppMetaData
		public RuleCall getAppDataAppMetaDataParserRuleCall_0() { return cAppDataAppMetaDataParserRuleCall_0; }
	}
	public class AppMetaDataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.AppMetaData");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cAppIDAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cAppIDIDTerminalRuleCall_0_0 = (RuleCall)cAppIDAssignment_0.eContents().get(0);
		private final Assignment cSpecificationsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSpecificationsAppSpecificationParserRuleCall_1_0 = (RuleCall)cSpecificationsAssignment_1.eContents().get(0);
		
		//AppMetaData:
		//	appID=ID
		//	specifications+=AppSpecification*
		//	//globalRequirements += GlobalRequirement
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//appID=ID specifications+=AppSpecification*
		public Group getGroup() { return cGroup; }
		
		//appID=ID
		public Assignment getAppIDAssignment_0() { return cAppIDAssignment_0; }
		
		//ID
		public RuleCall getAppIDIDTerminalRuleCall_0_0() { return cAppIDIDTerminalRuleCall_0_0; }
		
		//specifications+=AppSpecification*
		public Assignment getSpecificationsAssignment_1() { return cSpecificationsAssignment_1; }
		
		//AppSpecification
		public RuleCall getSpecificationsAppSpecificationParserRuleCall_1_0() { return cSpecificationsAppSpecificationParserRuleCall_1_0; }
	}
	public class AppSpecificationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.AppSpecification");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cONKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTriggerAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTriggerElementParserRuleCall_1_0 = (RuleCall)cTriggerAssignment_1.eContents().get(0);
		private final Keyword cIFKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cConditionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConditionElementParserRuleCall_3_0 = (RuleCall)cConditionAssignment_3.eContents().get(0);
		private final Keyword cDOKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cActionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cActionElementParserRuleCall_5_0 = (RuleCall)cActionAssignment_5.eContents().get(0);
		
		//AppSpecification:
		//	'ON' trigger+=Element*
		//	'IF' condition+=Element*
		//	'DO' action+=Element;
		@Override public ParserRule getRule() { return rule; }
		
		//'ON' trigger+=Element* 'IF' condition+=Element* 'DO' action+=Element
		public Group getGroup() { return cGroup; }
		
		//'ON'
		public Keyword getONKeyword_0() { return cONKeyword_0; }
		
		//trigger+=Element*
		public Assignment getTriggerAssignment_1() { return cTriggerAssignment_1; }
		
		//Element
		public RuleCall getTriggerElementParserRuleCall_1_0() { return cTriggerElementParserRuleCall_1_0; }
		
		//'IF'
		public Keyword getIFKeyword_2() { return cIFKeyword_2; }
		
		//condition+=Element*
		public Assignment getConditionAssignment_3() { return cConditionAssignment_3; }
		
		//Element
		public RuleCall getConditionElementParserRuleCall_3_0() { return cConditionElementParserRuleCall_3_0; }
		
		//'DO'
		public Keyword getDOKeyword_4() { return cDOKeyword_4; }
		
		//action+=Element
		public Assignment getActionAssignment_5() { return cActionAssignment_5; }
		
		//Element
		public RuleCall getActionElementParserRuleCall_5_0() { return cActionElementParserRuleCall_5_0; }
	}
	public class ElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.Element");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMeaningAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cMeaningIDTerminalRuleCall_0_0 = (RuleCall)cMeaningAssignment_0.eContents().get(0);
		private final Assignment cConceptAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cConceptConceptParserRuleCall_1_0 = (RuleCall)cConceptAssignment_1.eContents().get(0);
		
		//Element:
		//	meaning=ID
		//	concept=Concept;
		@Override public ParserRule getRule() { return rule; }
		
		//meaning=ID concept=Concept
		public Group getGroup() { return cGroup; }
		
		//meaning=ID
		public Assignment getMeaningAssignment_0() { return cMeaningAssignment_0; }
		
		//ID
		public RuleCall getMeaningIDTerminalRuleCall_0_0() { return cMeaningIDTerminalRuleCall_0_0; }
		
		//concept=Concept
		public Assignment getConceptAssignment_1() { return cConceptAssignment_1; }
		
		//Concept
		public RuleCall getConceptConceptParserRuleCall_1_0() { return cConceptConceptParserRuleCall_1_0; }
	}
	public class ConceptElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.Concept");
		private final Assignment cReferenceNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cReferenceNameIDTerminalRuleCall_0 = (RuleCall)cReferenceNameAssignment.eContents().get(0);
		
		//Concept:
		//	referenceName=ID
		//	//value = Value	
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//referenceName=ID
		public Assignment getReferenceNameAssignment() { return cReferenceNameAssignment; }
		
		//ID
		public RuleCall getReferenceNameIDTerminalRuleCall_0() { return cReferenceNameIDTerminalRuleCall_0; }
	}
	
	
	private final RunTimeModelElements pRunTimeModel;
	private final AppMetaDataElements pAppMetaData;
	private final AppSpecificationElements pAppSpecification;
	private final ElementElements pElement;
	private final ConceptElements pConcept;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRunTimeModel = new RunTimeModelElements();
		this.pAppMetaData = new AppMetaDataElements();
		this.pAppSpecification = new AppSpecificationElements();
		this.pElement = new ElementElements();
		this.pConcept = new ConceptElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("nii.bigclout.ecaadapter.Dsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//RunTimeModel:
	//	appData+=AppMetaData*
	//	//envData += EnvironmentMetaData*	
	//;
	public RunTimeModelElements getRunTimeModelAccess() {
		return pRunTimeModel;
	}
	
	public ParserRule getRunTimeModelRule() {
		return getRunTimeModelAccess().getRule();
	}
	
	//AppMetaData:
	//	appID=ID
	//	specifications+=AppSpecification*
	//	//globalRequirements += GlobalRequirement
	//;
	public AppMetaDataElements getAppMetaDataAccess() {
		return pAppMetaData;
	}
	
	public ParserRule getAppMetaDataRule() {
		return getAppMetaDataAccess().getRule();
	}
	
	//AppSpecification:
	//	'ON' trigger+=Element*
	//	'IF' condition+=Element*
	//	'DO' action+=Element;
	public AppSpecificationElements getAppSpecificationAccess() {
		return pAppSpecification;
	}
	
	public ParserRule getAppSpecificationRule() {
		return getAppSpecificationAccess().getRule();
	}
	
	//Element:
	//	meaning=ID
	//	concept=Concept;
	public ElementElements getElementAccess() {
		return pElement;
	}
	
	public ParserRule getElementRule() {
		return getElementAccess().getRule();
	}
	
	//Concept:
	//	referenceName=ID
	//	//value = Value	
	//;
	public ConceptElements getConceptAccess() {
		return pConcept;
	}
	
	public ParserRule getConceptRule() {
		return getConceptAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
