/**
 * generated by Xtext 2.13.0
 */
package nii.bigclout.ecaadapter.validation;

import nii.bigclout.ecaadapter.validation.AbstractDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DslValidator extends AbstractDslValidator {
}
